// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuAoX7r0eAzCRj6CMPMv3elR4ddcYrshA',
    appId: '1:168920976692:web:e7e8f963ed8e4fec422961',
    messagingSenderId: '168920976692',
    projectId: 'nusantara-deb00',
    authDomain: 'nusantara-deb00.firebaseapp.com',
    storageBucket: 'nusantara-deb00.firebasestorage.app',
    measurementId: 'G-ZBRWNZW3V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7qYvRYqglqVFLsBNpsedInXGiWBO-Qg4',
    appId: '1:168920976692:android:baa7069e9d40aba6422961',
    messagingSenderId: '168920976692',
    projectId: 'nusantara-deb00',
    storageBucket: 'nusantara-deb00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuX-GWzL-iU2HAj5z23B84Ys-3oH5b8K0',
    appId: '1:168920976692:ios:6e9fdc2a609bfea8422961',
    messagingSenderId: '168920976692',
    projectId: 'nusantara-deb00',
    storageBucket: 'nusantara-deb00.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuX-GWzL-iU2HAj5z23B84Ys-3oH5b8K0',
    appId: '1:168920976692:ios:6e9fdc2a609bfea8422961',
    messagingSenderId: '168920976692',
    projectId: 'nusantara-deb00',
    storageBucket: 'nusantara-deb00.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuAoX7r0eAzCRj6CMPMv3elR4ddcYrshA',
    appId: '1:168920976692:web:df10b3611e1c8edb422961',
    messagingSenderId: '168920976692',
    projectId: 'nusantara-deb00',
    authDomain: 'nusantara-deb00.firebaseapp.com',
    storageBucket: 'nusantara-deb00.firebasestorage.app',
    measurementId: 'G-B3GSR3WQZJ',
  );
}
